ci:
  autofix_prs: true
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes
  autoupdate_commit_msg: |
    [pre-commit.ci] pre-commit autoupdate
  autoupdate_schedule: monthly

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.110.8
    hooks:
      - id: renovate-config-validator
        args: [--strict]
        files: ^\.github/renovate\.json$

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.25
    hooks:
      - id: validate-pyproject
