coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_critical_paths: true
