name: Build distributions

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test distributions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Required for setuptools-scm to derive the version from Git history
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Build
        run: uv build

      # Run the full test suite against the built distributions to ensure integrity
      - name: Test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl --with pytest pytest -o addopts='--tb=short --strict-markers --strict-config'

      - name: Test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz --with pytest pytest -o addopts='--tb=short --strict-markers --strict-config'

      - name: Upload distributions
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/
